<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>TimeTracker.Core</RootNamespace>
    <AssemblyName>TimeTracker.Core</AssemblyName>
  </PropertyGroup>

</Project>
